version: '3'
services:
  app:
    build: .
    container_name: my_python_app
    ports:
      - "5000:5000"
    environment:
      - ENVIRONMENT=DEV
      - HOST=0.0.0.0
      - PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    command: sh -c "sleep 5 && python hello.py" # Wait for Redis to start

  redis:
    image: "redis:5.0"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
